In [4]:
import numpy as  np
import pandas as pd

b = np.array([[[1,2,3],[3,2,1]], [[4, 5, 6],[5,6,7]]])
type(b)
print(b.ndim)
print(b)
print(b.shape)
print(b.size)

a = np.arange(0, 10, 2)
print(a)
type(a)

In [45]:
a = np.array([[1,2,3], [4,5,6]])
b = np.append(a, [[7, 8 , 9]], axis = 0)
c = np.append(b, [[4],[6],[ 6]], axis = 1)
new_row = np.array([3, 2,1])
b = np.insert(b, 0, new_row, axis = 0)
print(b)

[[3 2 1]
 [1 2 3]
 [4 5 6]
 [7 8 9]]

In [43]:
a = np.arange(1, 25, 3)
print(f"array: {a}")
print(f"Max: {a.max()}")
print(f"Min: {a.min()}")
print(f"Mean: {a.mean()}")
print(f"Std: {a.std()}")
print(f"Median: {np.median(a)}")

array: [ 1  4  7 10 13 16 19 22]
Max: 22
Min: 1
Mean: 11.5
Std: 6.87386354243376
Median: 11.5

In [51]:
a = np.arange(1, 10)
a = a.reshape(3, 3)
print(a)
print(a.mean(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]

In [56]:
np.random.seed(12)
a = np.random.randint(1, 100, size=(3, 3))
print(a)

[[42 15 51]
 [61 98 32]
 [71 73 15]]

In [67]:
se1 = pd.Series(data= ['USA', 'Nepal', "China"], name='Country')
se1

0      USA
1    Nepal
2    China
Name: Country, dtype: object

In [71]:
# Create a DataFrame with 10 countries, capitals, and populations
df1 = pd.DataFrame(
    {
        "Country": [
            "United States", "Canada", "Germany", "France", "Italy",
            "Brazil", "India", "China", "Australia", "Japan"
        ],
        "Capital": [
            "Washington, D.C.", "Ottawa", "Berlin", "Paris", "Rome",
            "Bras√≠lia", "New Delhi", "Beijing", "Canberra", "Tokyo"
        ],
        "Population": [
            331002651, 37742154, 83783942, 67848973, 60264646,
            212559417, 1380004385, 1393409038, 25499884, 126476461
        ]
    }
)

df1.dtypes

Country       object
Capital       object
Population     int64
dtype: object

df1.loc[df1['Population'] > 1000000000]

In [78]:
new_df = df1[df1['Country'] == 'United States' ]
new_df